### ISSUE TITLE
Scripts: re-add

### ISSUE THREAD

**Issue by joeflack4** [jkpr/QTools2#13]
## Description
I got the following feedback from Ann (on Slack, after fixing an issue she had):
> **Ann Rogers [8:48 AM]**
> Hi Joe, Guy and I are having a problem with Qtools2
> Under the "Usage" section you have "The easiest way to use qtools2 is to use a file from the scripts folder of this repository." But the link to the repository returns a 404 error
> 
> **Ann Rogers [9:23 AM]**
> so we found a work around for that
> we are using the command C:\Python27\python.exe -m qtools2 (edited)
> it pulls up the GUI
> 
> **Joe Flack [9:25 AM]**
> yeah you'll just have to use the command line. looks like the double click script was removed. i think james removed it. if i had to guess why, it was because it wasn't consistent

## Task List
- [ ] 1. Re-add `scripts/` subdir from the state they were in in the last commit before they were removed.
- [ ] 2. For any shell scripts that do not have a Windows equivalent and should, make them.
- [ ] 3. Check that scripts work; might as well implement some TDD here in the mean time.
